source :rubygems
source "http://rubygems.org"
source :rubyforge
source "http://gems.rubyforge.org"
source :gemcutter
source "http://gemcutter.org"

gem 'sinatra'
gem 'jsmin'
gem 'cssmin'
gem 'pg'
gem 'do_postgres'
gem 'data_mapper'
gem 'dm-core'
gem 'dm-validations'
gem 'dm-migrations'
gem 'dm-timestamps'
gem 'dm-serializer'
gem 'dm-postgres-adapter'